### PR TITLE
Refactor development configuration

### PR DESCRIPTION
**Pull request by hvelarde**

### CODE REVIEW

**Comment by davisagli** [comment]
Thanks!

**Comment by hvelarde** [comment]
you have to enable Travis and Coveralls for this to work

**Comment by davisagli** [comment]
Feel free, I'm off for the weekend without much internet.

David Glick
(mobile)

**Comment by hvelarde** [comment]
I can't, I have no admin rights on your repos :-)

have a nice weekend!

**Comment by davisagli** [comment]
Ha, I forgot it wasn't in the collective. I'll take care of it on Monday.

David Glick
(mobile)

**Pull request merged**
